//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrmTracker.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class factions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal factions() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrmTracker.Ressources.factions", typeof(factions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Crystal.
        /// </summary>
        internal static string CrystalLabel {
            get {
                return ResourceManager.GetString("CrystalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Crystal Bloom.
        /// </summary>
        internal static string CrystalTooltip {
            get {
                return ResourceManager.GetString("CrystalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deldrimor.
        /// </summary>
        internal static string DeldrimorLabel {
            get {
                return ResourceManager.GetString("DeldrimorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deldrimor Dwarves.
        /// </summary>
        internal static string DeldrimorTooltip {
            get {
                return ResourceManager.GetString("DeldrimorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ebon.
        /// </summary>
        internal static string EbonLabel {
            get {
                return ResourceManager.GetString("EbonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ebon Vanguard.
        /// </summary>
        internal static string EbonTooltip {
            get {
                return ResourceManager.GetString("EbonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exalted.
        /// </summary>
        internal static string ExaltedLabel {
            get {
                return ResourceManager.GetString("ExaltedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exalted.
        /// </summary>
        internal static string ExaltedTooltip {
            get {
                return ResourceManager.GetString("ExaltedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kodan.
        /// </summary>
        internal static string KodanLabel {
            get {
                return ResourceManager.GetString("KodanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kodan.
        /// </summary>
        internal static string KodanTooltip {
            get {
                return ResourceManager.GetString("KodanTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Legion.
        /// </summary>
        internal static string LegionLabel {
            get {
                return ResourceManager.GetString("LegionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flame Legion.
        /// </summary>
        internal static string LegionTooltip {
            get {
                return ResourceManager.GetString("LegionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Olmakhan.
        /// </summary>
        internal static string OlmakhanLabel {
            get {
                return ResourceManager.GetString("OlmakhanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Olmakhan.
        /// </summary>
        internal static string OlmakhanTooltip {
            get {
                return ResourceManager.GetString("OlmakhanTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Skritt.
        /// </summary>
        internal static string SkrittLabel {
            get {
                return ResourceManager.GetString("SkrittLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Skritt.
        /// </summary>
        internal static string SkrittTooltip {
            get {
                return ResourceManager.GetString("SkrittTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tengu.
        /// </summary>
        internal static string TenguLabel {
            get {
                return ResourceManager.GetString("TenguLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tengu.
        /// </summary>
        internal static string TenguTooltip {
            get {
                return ResourceManager.GetString("TenguTooltip", resourceCulture);
            }
        }
    }
}
