//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrmTracker.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class maps {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal maps() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrmTracker.Ressources.maps", typeof(maps).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bloodtide.
        /// </summary>
        internal static string BloodtideLabel {
            get {
                return ResourceManager.GetString("BloodtideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bloodtide Coast.
        /// </summary>
        internal static string BloodtideTooltip {
            get {
                return ResourceManager.GetString("BloodtideTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Brisban.
        /// </summary>
        internal static string BrisbanLabel {
            get {
                return ResourceManager.GetString("BrisbanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Brisban Wildlands.
        /// </summary>
        internal static string BrisbanTooltip {
            get {
                return ResourceManager.GetString("BrisbanTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Caledon.
        /// </summary>
        internal static string CaledonLabel {
            get {
                return ResourceManager.GetString("CaledonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Caledon Forest.
        /// </summary>
        internal static string CaledonTooltip {
            get {
                return ResourceManager.GetString("CaledonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Doric.
        /// </summary>
        internal static string DoricLabel {
            get {
                return ResourceManager.GetString("DoricLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lake Doric.
        /// </summary>
        internal static string DoricTooltip {
            get {
                return ResourceManager.GetString("DoricTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fireheart.
        /// </summary>
        internal static string FireheartLabel {
            get {
                return ResourceManager.GetString("FireheartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fireheart Rise.
        /// </summary>
        internal static string FireheartTooltip {
            get {
                return ResourceManager.GetString("FireheartTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gendarran.
        /// </summary>
        internal static string GendarranLabel {
            get {
                return ResourceManager.GetString("GendarranLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gendarran Fields.
        /// </summary>
        internal static string GendarranTooltip {
            get {
                return ResourceManager.GetString("GendarranTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Metrica.
        /// </summary>
        internal static string MetricaLabel {
            get {
                return ResourceManager.GetString("MetricaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Metrica Province.
        /// </summary>
        internal static string MetricaTooltip {
            get {
                return ResourceManager.GetString("MetricaTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ruins.
        /// </summary>
        internal static string RuinsLabel {
            get {
                return ResourceManager.GetString("RuinsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fields of Ruin.
        /// </summary>
        internal static string RuinsTooltip {
            get {
                return ResourceManager.GetString("RuinsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Snowden.
        /// </summary>
        internal static string SnowdenLabel {
            get {
                return ResourceManager.GetString("SnowdenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Snowden Drifts.
        /// </summary>
        internal static string SnowdenTooltip {
            get {
                return ResourceManager.GetString("SnowdenTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thunderhead.
        /// </summary>
        internal static string ThunderheadLabel {
            get {
                return ResourceManager.GetString("ThunderheadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thunderhead Peaks.
        /// </summary>
        internal static string ThunderheadTooltip {
            get {
                return ResourceManager.GetString("ThunderheadTooltip", resourceCulture);
            }
        }
    }
}
